<?php

/**
 * @file
 * Contains composer_patches.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function composer_patches_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the composer_patches module.
    case 'help.page.composer_patches':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
